export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const ADD_SERVICE_REQUEST    = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE    = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS    = 'ADD_SERVICE_SUCCESS';

export const REMOVE_SERVICE_REQUEST    = 'REMOVE_SERVICE_REQUEST';
export const REMOVE_SERVICE_SUCCESS    = 'REMOVE_SERVICE_SUCCESS';
export const REMOVE_SERVICE_FAILURE    = 'REMOVE_SERVICE_FAILURE';

export const FETCH_EDIT_REQUEST    = 'FETCH_EDIT_REQUEST';
export const FETCH_EDIT_SUCCESS    = 'FETCH_EDIT_SUCCESS';
export const FETCH_EDIT_FAILURE    = 'FETCH_EDIT_FAILURE';

export const UPDATE_SERVICE_REQUEST  = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_FAILURE = 'UPDATE_SERVICE_FAILURE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';

export const REMOVE_SERVICE         = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD   = 'CHANGE_SERVICE_FIELD';

export const EDIT_SERVICE = "EDIT_SERVICE";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const CANCEL_UPDATE = "CANCEL_UPDATE";